kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-jobs
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-can-create-jobs
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: create-jobs
  apiGroup: rbac.authorization.k8s.io